name: Deploy Website (preview)

on:
  push:
    branches:
      - preview

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SERVER_USER: corkcl
      SERVER_HOST: ftp.cluster023.hosting.ovh.net
      $SERVER_ADDRESS: $SERVER_USER@$SERVER_HOST

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build the website
        run: npm run build

      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H $SERVER_ADDRESS >> ~/.ssh/known_hosts

      - name: Deploy to server
        env:
          SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
        run: |
          scp -r dist $SERVER_ADDRESS:/home/$SERVER_USER/dist-${{ github.sha }}

      - name: Update OVH root folder
        run: |
          ssh $SERVER_ADDRESS "ln -sfn /home/$SERVER_USER/dist-${{ github.sha }} /home/$SERVER_USER/current"
